image: openjdk:11

pipelines:
  tags:
    boilerplate-dev-*:
      - step:
          services:
            - docker
          script:
            - export IMAGE=react-boilerplate:${BITBUCKET_TAG}
            - docker build -t react-boilerplate:${BITBUCKET_TAG} .
            - pipe: atlassian/xx-image:0.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: $IMAGE
                TAGS: '${BITBUCKET_TAG} dev latest'
      - step:
          name: "Deploy to Kubernetes"
          script:
            - git clone {bitbucket}
            - cd {folder} && git checkout develop && git pull
            - cd ..
            - pipe: atlassian/xx-kubectl-run:0.1
              variables:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                CLUSTER_NAME: "boilerplate-dev"
                KUBECTL_COMMAND: "rollout restart deployment react-boilerplate"
                DEBUG: "true"
                KUBECTL_ARGS:
                  - "-react-boilerplate-dev"
definitions:
  services:
    docker:
      memory: 3072
    
