export const DRAWER_MENU_LABEL = {
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  BANK_STATEMENT_UPLOAD: 'BANK_STATEMENT_UPLOAD',
  // DASHBOARD: 'DASHBOARD',
  // KANBAN: 'KANBAN',
  // USERS: 'USERS',
  // PLAY_BACKGROUND: 'PLAY_BACKGROUND',

  // PRODUCT: 'PRODUCT',
  // PRODUCT_ADD: 'PRODUCT_ADD',
  // PRODUCT_LIST: 'PRODUCT_LIST',
};
